//AUTORES: THAÍS RIGUETI E JOSÉ VITOR IZAC
//https://www.youtube.com/watch?v=4eyFa_Kp0UM
//https://github.com/splintermeister/prova-20-09-2022.cs

using System;
using System.Collections.Generic;
using System.Linq;

bool InvalidInput = false;
Home:
Console.Clear();
Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
Console.WriteLine();
Console.WriteLine("O sonoplasta do Rodrigo Faro perdeu algumas palavras.");
Console.WriteLine();
Console.WriteLine("Você vai ajudar ele a encontar as palavras perdidas?");
Console.WriteLine();
Console.WriteLine("<SIM>");
Console.WriteLine("<NAO>");
Console.WriteLine("<REGRAS>");
Console.WriteLine();
if (InvalidInput)
{
    Console.WriteLine("Entrada inválida. Tente novamente.");
    InvalidInput = false;
}
Console.Write(">");
switch (Console.ReadLine())
{
    case "SIM": Play1(); goto Home;
    case "NAO": Quit(); goto Home;
    case "REGRAS": Info(); goto Home;
    default: InvalidInput = true; goto Home;
};

void Info()
{
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("Regras:");
    Console.WriteLine();
    Console.WriteLine("Digite as dez palavras perdidas pelo sonoplasta do Rodrigo Faro.");
    Console.WriteLine();
    Console.WriteLine("As palavras podem estar escondidas verticalmente, horizontalmente ou diagonalmente dentro da grade.");
    Console.WriteLine();
    Console.WriteLine("<ENTER> para retornar ao menu.");
    Console.WriteLine();
    Console.WriteLine("Boa sorte!!!");
    Console.ReadLine();
}

void Quit()
{
    bool InvalidInput = false;
Quit:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("Você tem certeza que quer abandonar o sonoplasta?");
    Console.WriteLine();
    Console.WriteLine("<SIM> abandonar o sonoplasta.");
    Console.WriteLine("<NAO> para retornar ao menu.");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "SIM": Console.Clear(); Environment.Exit(0); return;
        case "NAO": return;
        default: InvalidInput = true; goto Quit;
    };
}

void Play1()
{
    bool InvalidInput = false;
Play1:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E U F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T E J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U P H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J A L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X C Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A A F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K V N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S A K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D L A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J O D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L E L E G O S T A J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D U\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L I\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O I\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y R A T I N H O");
    Console.WriteLine();
    Console.WriteLine("Encontre <UEPA>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "UEPA": Play2(); goto Play1;
        default: InvalidInput = true; goto Play1;
    };
}
void Play2()
{
    bool InvalidInput = false;
Play2:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X C Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A A F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K V N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S A K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D L A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J O D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L E L E G O S T A J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D U\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L I\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O I\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y R A T I N H O");
    Console.WriteLine("Encontre <RATINHO>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "RATINHO": Play3(); ; goto Play2;
        default: InvalidInput = true; goto Play2;
    };
}
void Play3()
{
    bool InvalidInput = false;
Play3:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X C Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A A F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K V N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S A K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D L A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J O D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L E L E G O S T A J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D U\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L I\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O I\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <CAVALO>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "CAVALO": Play4(); ; goto Play3;
        default: InvalidInput = true; goto Play3;
    };
}
void Play4()
{
    bool InvalidInput = false;
Play4:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L E L E G O S T A J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D U\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L I\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O I\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <UII>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "UII": Play5(); ; goto Play4;
        default: InvalidInput = true; goto Play4;
    };
}
void Play5()
{
    bool InvalidInput = false;
Play5:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L E L E G O S T A J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <ELEGOSTA>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "ELEGOSTA": Play6(); ; goto Play5;
        default: InvalidInput = true; goto Play5;
    };
}
void Play6()
{
    bool InvalidInput = false;
Play6:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A T O M E O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <TOME>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "TOME": Play7(); ; goto Play6;
        default: InvalidInput = true; goto Play6;
    };
}
void Play7()
{
    bool InvalidInput = false;
Play7:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A * * * * O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P D A N Ç A G A T I N H O D A N Ç A T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <DANÇAGATINHODANÇA>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "DANÇAGATINHODANÇA": Play8(); ; goto Play7;
        default: InvalidInput = true; goto Play7;
    };
void Play8()
{
    bool InvalidInput = false;
Play8:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L Q U E I S S O M E * F I L H O C A L M A Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A * * * * O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P * * * * * * * * * * * * * * * * * T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <QUEISSOMEUFILHOCALMA>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "QUEISSOMEUFILHOCALMA": Play9(); ; goto Play8;
        default: InvalidInput = true; goto Play8;
    };
}
void Play9()
{
    bool InvalidInput = false;
Play9:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L * * * * * * * * * * * * * * * * * * * * Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A * * * * O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P * * * * * * * * * * * * * * * * * T U G H F I O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L R S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F R A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G A S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <IRRA>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "IRRA": Play10(); ; goto Play9;
        default: InvalidInput = true; goto Play9;
    };
}
void Play10()
{
    bool InvalidInput = false;
Play10:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();   
    Console.WriteLine("\r\n J K L A Ç G H J K L * * * * * * * * * * * * * * * * * * * * Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A * * * * O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P * * * * * * * * * * * * * * * * * T U G H F * O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L * S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F * A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G * S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H P A R E H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Encontre <PARE>");
    Console.WriteLine();
    if (InvalidInput)
    {
        Console.WriteLine("Entrada inválida. Tente novamente.");
    }
    Console.Write(">");
    switch (Console.ReadLine())
    {
        case "PARE": Win(); ; goto Play10;
        default: InvalidInput = true; goto Play10;
    };
}
void Win()
{
Win:
    Console.Clear();
    Console.WriteLine("\r\n                                     ,▄▄▄▄▄▄█▄▄▄▓▓▓▄▄╓\r\n                                ,╦█████████████████████▄▄\r\n                             ▄▄████████████████████████████▄\r\n                           ▄██████████████████████████████████╕\r\n                         ,███████▓███████▓███████████▓█████████▌\r\n                        ▄█████████████████▓▓████████████████████.\r\n                       ███████▓▓████████████▓███████████▓▓███████\r\n                      ▐██████▓███▓▓▓█████████▓▓▓████████▓▓███████▌\r\n                      ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▓███████████\r\n                      ██████▓╜╜╜╙``  `  `````╙╙╙╜▒╢▓▓▓▓▓▓▓▓▓██████L\r\n                      ████▓▒                      '░░▒▒▒▒▒╣╢▓█████\r\n                      ▐██▓▓░                          ░▒▒▒▒╢▒▓████\r\n                      ▐██▓╣`                           ░░▒▒▒╢▓▓███\r\n                      ▐██▓╣░                           ░░▒▒▒▒╫▓███\r\n                      ▐██▓▒                          ,░░▒▒▒▒╢╫▓███\r\n                      ▓██▌░░░»╫╣╝╩╨▓▓╬╣▒¿░      ╓╫▓▓▓▓▓▓▓▓▓▒╣╢▓███\r\n                      ╟▓█▌░░ ╙ ,╓╦m▄▄▄▒▒▒     ▒@▓╜▒▒╖╓╓▒╙▒▒╢╢╣▓██▓\r\n                      ╟▒▒▌▒   ╙╨▀└▀█▀▒▓╝╙`   j▓▓╣▓▓╙███▓▓▓▒╢╢╫▓█╣█\r\n                      ▒╣╣▌▒      ─≡mß╨╜`      ▒▓▒▒ ~.▒▒▒▒▒╢╣╢╢╫▓▓▌\r\n                      ║╫ ▒░                   ░▒░░      `░▒▒▒╢╢▓█\r\n                      ║▒▒║▒░          ,       ░▒▒Ñ,       ░▒▒╢╫█▓\r\n                      ╚▒░]▒▒░     ,╖@╜        ░▒░░▓@,   .░▒░▒╢╣▓▓Γ\r\n                        \" ▒▒▒   ,▒╫▓▒  `≡▄  , ░g@▄█▓▒╖  ░▒▒▒╢╫▓▀\"\r\n                          ▒▒▒▒░░▒╫╣▒      '╖▒▒▓▓▓▓▓▓╣▒Ñ▒▒▒▒▒╢╢\r\n                          ╚▒▒▒░]▓╬▓▄▄╖wq,,. ,▒║╢▒▒▒▒╣╢Ñ╢░▒▒╢╢╢\r\n                           ╣▒▒░ ░▒╜`╙,  `  ╙╜`▀  ▐▓█▀▒░░░▒▒▒╢╛\r\n                            ▓▒░░       ``─╤╦╥╦╦╦@▒╜▒▒▒▒▒▒▒▒╢╜\r\n                            ]▒▒░          ¿░░╓▒▒▒▒▒▒░░▒▒▒▒▒\r\n                            ]▒▒▒             ░░▒▒▒▒░░▒▒▒▒▒▒\r\n                             ▒░`░              '`░ ░▒▒▒▒▒▒▒▓╖\r\n                             ▒░   ░░           ░,░▒▒▒▒▒▒▒╢▒▓▓▓,\r\n                             ▒░░    ╙▒╖╖╓╖▒.,▒▒▒▒▒░░▒▒╢▒▒▒▒██▓╢╗,\r\n                             ▓▒░░     ╙░╙╨╫▓▓▓▓▒▒░░░▒▒▒▒▒▒▒██▌╜` ╚▒@╦╖\r\n                             ]▓▒░       `░░▒▒╢╢▒▒▒░░▒▒▒▒╢▓▓▓██µ   ╙┐' ``▒%╓,\r\n                              ▐▓╖            ░░░░░▒▒▒▒╢╢╢▓▓▓▓██    ╙▒░       `\r\n                               ▓▓▒░        ░░░▒░▒▒▒╣▒╢╣╢╢╣▓▓▓▓▓▌     ▒   '         \"");
    Console.WriteLine();
    Console.WriteLine("\r\n J K L A Ç G H J K L * * * * * * * * * * * * * * * * * * * * Ç A D H Ç J K H Ç A\r\n J K D G B F I A U S D G B A S D O N T * J D K I O H J F O I H F O I D H O S I D\r\n F O I H F O I D S F O H U I G J F I U * H F J D H F O P I B H F I G H H V G H K\r\n H A D G F L A J H F J H A S D J F H J * L S D F H K K K K K K R J L D D J U L T\r\n J Ç K F S D I F G Ç U G U G N W I O Ç H G S D J K L F B H D S K T D A H Ç J N V\r\n Ç C N V Ç D H F G A Ç I H A Ç U F G Ç A I S H F N Ç K L S D N F Ç A F H A Ç U H\r\n S O I H F B W E Ç J F B H Ç W E O A I J H F J J B D K J A S B H F I S D G B J F\r\n J K B F I S D G H A L K N F G J K G H A P O H G J D F J J H I K H G O W J H S J\r\n K L D B N I L J A H J K G F J K L G K L S B N K J D B F D K J A * * * * O Ç I F\r\n B H T H A I S J B H J K S D F B H O S D A F I A S B H D F Ç J B K F V J K Ç B H\r\n O L M K A S J Ç N K J S J K L F N D S Ç O A H S L F G M N B M Ç J J K K H V Y J\r\n J S D B H A Ç J B F I P * * * * * * * * * * * * * * * * * T U G H F * O S D N D\r\n U I G A Y E S C O N D I D O X * Y H V L D F G A L S J I D F H J K L * S D G F L\r\n J D G H F I L Ç A G K S J L Ç A * F K J L A S D G F J K A G H L K F * A S D L J\r\n K F G L A D U I F G L A S K G F K * N J K B H A S D K L J F I L F G * S D J I F\r\n J K Ç A S D F B H J K A S D L G A S * K J F B H Ç A S O I H C B G Ç D L K S F G\r\n H Ç K O A S D F H G A Õ F G A D F G D * A G A D S F G D F G A S J D F I O P H Í\r\n G S D F J O G A P S O F J P S D H I O J * D J G S D F K O J A L G Ç J K A S D G\r\n F A Y L H S G F A S D F G B A U Y L E R F V H L Y S D V H F L A S D T F G F H F\r\n G J L * * * * * * * * J H A Ç F A D Ç H F A U P G H P Ç H I G Ç D F G A D G D *\r\n F G A D F G J Ç D K L H A S Ç L K G H Ç L A S D F K G H A Ç D F K L G H Ã K L *\r\n H D F G A D F G A F D G D F G K Õ A H G O I D F J G Ã P F L J G J H A F F K O *\r\n J K L A S D H F Ç J K D H A S D I O Ç F H Ç K J A H K L J H N V N J K X K J F Ç\r\n K O D H F Ç A S D H F Ç J I A S H * * * * H Ç B H G J A K S D V H J L V L J G Y\r\n A S D F G A D S A J B D Ç S A J K F A B H S L D K F H A L Ç S J K D F B Ç G K K\r\n J K A S D F H I Ç A J S H G Ç A J K L G H Ç K L J B H F G B A L Y * * * * * * *");
    Console.WriteLine();
    Console.WriteLine("Parabéns! Você salvou o emprego do sonoplasta!");
    Console.WriteLine();
    Console.WriteLine("<SAIR> para fechar o jogo.");
    Console.WriteLine();
    switch (Console.ReadLine())
    {
        case "SAIR": Console.Clear(); Environment.Exit(0); return;
        default: InvalidInput = true; goto Win;
    };
}
}
